language: rust
sudo: required

rust:
  - stable
  - beta
  - nightly

env:
  - POSTGRESQL_VERSION=9.4 RUST_BACKTRACE=1
  - POSTGRESQL_VERSION=9.5 RUST_BACKTRACE=1
  - POSTGRESQL_VERSION=9.6 RUST_BACKTRACE=1
  - POSTGRESQL_VERSION=10 RUST_BACKTRACE=1
  - POSTGRESQL_VERSION=11 RUST_BACKTRACE=1

services:
  - docker

before_install:
  - docker pull postgres:$POSTGRESQL_VERSION
  - docker run -d postgres:$POSTGRESQL_VERSION

script:
  - cargo build --verbose --all --all-features
  - cargo test --verbose --all --all-features -- --test-threads=1

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

notifications:
  email:
    on_success: never