language: rust
dist: trusty
sudo: required

rust:
  - stable
  - beta
  - nightly

env:
  - POSTGRESQL_VERSION=9.4
  - POSTGRESQL_VERSION=9.5
  - POSTGRESQL_VERSION=9.6
  - POSTGRESQL_VERSION=10
  - POSTGRESQL_VERSION=11

services:
  - docker

before_install:
  - docker pull postgres:$POSTGRESQL_VERSION
  - sudo /etc/init.d/postgresql stop
  - docker run -d postgres:$POSTGRESQL_VERSION

script:
  - cargo build --verbose --all --all-features
  - cargo test --verbose --all --all-features -- --test-threads=1

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

notifications:
  email:
    on_success: never