[package]
name = "psqlpackage"
version = "0.1.0"
authors = ["Paul Mason <paul@form1.co.nz>"]
build = "build.rs"

[dependencies]
chrono = { version = "0.2", features = ["serde"] }
clap = "2.20.0"
lalrpop-util = "0.12.5"
serde = "0.9"

[build-dependencies]
lalrpop = "0.12.5"