[package]
name = "psqlpackage"
version = "0.1.0"
authors = ["Paul Mason <paul@form1.co.nz>"]

[dependencies]
chrono = { version = "0.3", features = ["serde"] }
clap = "2.20.5"
pg-dacpac = { path = "../dacpac/" }