[package]
name = "psqlpack"
version = "0.1.0"
authors = ["Paul Mason <paul@form1.co.nz>"]
build = "build.rs"

[dependencies]
error-chain = "0.10"
lazy_static = "0.2"
lalrpop-util = "0.13"
slog = { version = "2", features = ["max_level_trace", "release_max_level_trace"] }
slog-stdlog = "2"
postgres = "0.15"
regex = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
walkdir = "1"
zip = "0.2"

[build-dependencies]
lalrpop = "0.13"

[dev-dependencies]
spectral = "0.6.0"
